#!/usr/bin/env python3
"""Generate deterministic Roboto Condensed GFX fonts for the EN/RU UI catalog.

The source variable TTF is vendored under the SIL Open Font License.  Both
sizes select the named Medium (weight 500) instance before rasterization.  The
generated font deliberately spans U+0020..U+0451 so TFT_eSPI's UTF-8 decoder
can index ASCII and Cyrillic directly.  Code points outside those two populated
ranges have zero-sized glyphs and consume no bitmap bytes.
"""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path

from PIL import ImageFont


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "firmware/leshy1/assets/fonts/roboto-condensed/RobotoCondensed-wght.ttf"
OUTPUT = ROOT / "firmware/leshy1/src/ui/fonts/RobotoCondensedGfx.h"
WEIGHT_NAME = "Medium"
FIRST = 0x20
LAST = 0x451
POPULATED = tuple(range(0x20, 0x7F)) + tuple(range(0x400, 0x452))


def pack_mask(mask: object) -> bytes:
    values = list(mask)
    packed = bytearray()
    value = 0
    bits = 0
    for pixel in values:
        value = (value << 1) | (1 if int(pixel) >= 128 else 0)
        bits += 1
        if bits == 8:
            packed.append(value)
            value = 0
            bits = 0
    if bits:
        packed.append(value << (8 - bits))
    return bytes(packed)


def build_font(name: str, pixel_size: int) -> tuple[list[str], list[str], int, int, int]:
    font = ImageFont.truetype(str(SOURCE), pixel_size)
    font.set_variation_by_name(WEIGHT_NAME)
    ascent, descent = font.getmetrics()
    bitmaps = bytearray()
    glyphs: list[str] = []
    populated = set(POPULATED)

    for codepoint in range(FIRST, LAST + 1):
        offset = len(bitmaps)
        if codepoint not in populated:
            glyphs.append(f"  {{{offset}, 0, 0, 0, 0, 0}}, // U+{codepoint:04X}")
            continue

        character = chr(codepoint)
        left, top, right, bottom = font.getbbox(character, anchor="ls")
        width = max(0, right - left)
        height = max(0, bottom - top)
        advance = max(1, round(font.getlength(character)))
        if width and height:
            mask = font.getmask(character, mode="L")
            bitmaps.extend(pack_mask(mask))
        glyph_label = (
            "SPACE" if codepoint == 0x20
            else "BACKSLASH" if codepoint == 0x5C
            else character
        )
        glyphs.append(
            f"  {{{offset}, {width}, {height}, {advance}, {left}, {top}}}, "
            f"// U+{codepoint:04X} {glyph_label}"
        )

    bitmap_lines: list[str] = []
    for start in range(0, len(bitmaps), 16):
        chunk = bitmaps[start : start + 16]
        bitmap_lines.append("  " + ", ".join(f"0x{value:02X}" for value in chunk) + ",")
    return bitmap_lines, glyphs, ascent, descent, len(bitmaps)


def render() -> str:
    source_hash = hashlib.sha256(SOURCE.read_bytes()).hexdigest()
    sections: list[str] = [
        "#pragma once",
        "",
        "// Generated by tools/generate_ui_gfx_font.py; do not edit by hand.",
        "// Roboto Condensed Medium (weight 500), Copyright 2011 Google Inc.; SIL OFL 1.1.",
        f"// Source SHA-256: {source_hash}",
        "// Glyph coverage: U+0020..U+007E and U+0400..U+0451.",
        "",
    ]
    for name, pixel_size in (("RobotoCondensedBody", 16), ("RobotoCondensedMeta", 12)):
        bitmap_lines, glyphs, ascent, descent, bitmap_bytes = build_font(name, pixel_size)
        sections.extend(
            [
                f"constexpr uint8_t k{name}Ascent = {ascent};",
                f"constexpr uint8_t k{name}Descent = {descent};",
                f"constexpr uint16_t k{name}BitmapBytes = {bitmap_bytes};",
                f"const uint8_t {name}Bitmaps[] PROGMEM = {{",
                *bitmap_lines,
                "};",
                "",
                f"const GFXglyph {name}Glyphs[] PROGMEM = {{",
                *glyphs,
                "};",
                "",
                f"const GFXfont {name} PROGMEM = {{",
                f"  (uint8_t*){name}Bitmaps,",
                f"  (GFXglyph*){name}Glyphs,",
                f"  0x{FIRST:04X}, 0x{LAST:04X}, {ascent + descent}",
                "};",
                "",
            ]
        )
    return "\n".join(sections)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if output is stale")
    args = parser.parse_args()
    generated = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != generated:
            raise SystemExit(f"stale generated font: {OUTPUT}")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(generated, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
