#pragma once

// The full legal / responsible-use notice shown on screen — the SAME terms as
// DISCLAIMER.md / DISCLAIMER.ru.md (keep them in sync). Array of paragraphs so the
// screen can wrap and scroll it. "" is a spacer; a line starting with '#' is a heading.
struct LegalDoc { const char* const* p; int n; };

static const char* const LEGAL_RU[] = {
    "Коротко — никогда не делай ничего из этого не со своим.",
    "",
    "# Только своё оборудование",
    "ESP32-Leshy — образовательная прошивка для исследования безопасности. Применяй её только к сетям, устройствам и радио, которые принадлежат тебе, или на тест которых есть явное письменное разрешение.",
    "",
    "Никогда не направляй эти инструменты на чужое: ни на Wi-Fi соседа, ни на чужой телефон, ни на чью-то сигнализацию, ворота, брелок или машину. Без исключений, без «просто проверить», без «всего один раз».",
    "",
    "# Законы разных стран — РАЗНЫЕ",
    "Что легально в одной стране, в другой — преступление. Правила про доступ к сетям, перехват сигналов и радиоизлучение различаются повсюду и меняются со временем.",
    "",
    "Ты обязан сам узнать и соблюдать законы своей юрисдикции — не предполагать, а проверять. Сомневаешься — считай, что нельзя, и не делай, пока не убедишься.",
    "",
    "# Ответственность — только на тебе",
    "Всю ответственность за использование несёт исключительно конечный пользователь — и никто иной. Авторы не отвечают ни за что: ни за ущерб, ни за юридические последствия. ПО поставляется «как есть», без гарантий.",
    "",
    "# Что сейчас в прошивке",
    "Всё в этой сборке — пассивное или защитное:",
    "",
    "Скан Wi-Fi и BLE — слушает то, что и так открыто вещается в эфир.",
    "",
    "Раскрытие скрытых имён — читает имя из служебных кадров, где оно и так идёт открытым текстом. Только приём.",
    "",
    "Детектор атак — считает чужие deauth-кадры, чтобы предупредить тебя. Только приём.",
    "",
    "# Наступательное — позже и за замком",
    "Часть будущих функций — активные (deauth своей сети для проверки устойчивости, глушение для стенда). Они будут в отдельном разделе под замком: доступ каждый раз потребует подтвердить, что оборудование твоё и что ты соблюдаешь закон. По умолчанию выключены.",
    "",
    "Про глушение: излучать глушилку в эфир незаконно почти везде — даже против своих устройств: помеха уходит в общий спектр и мешает всем. Поэтому — только экранированный стенд и под замком.",
    "",
    "# Приватность других",
    "Даже пассивное наблюдение может задевать чужую приватность. Не собирай данные о чужих устройствах, не следи за людьми, не публикуй чужие MAC и имена сетей.",
    "",
    "Продолжая, ты подтверждаешь: применяешь прошивку только к своему оборудованию, сам проверил законы своей страны и берёшь всю ответственность на себя.",
};

static const char* const LEGAL_EN[] = {
    "In short — never do any of this to anything that isn't yours.",
    "",
    "# Your own equipment only",
    "ESP32-Leshy is an educational security-research firmware. Use it only on networks, devices and radios you own, or that you have explicit written permission to test.",
    "",
    "Never point these tools at anything that isn't yours: not a neighbor's Wi-Fi, not someone else's phone, not a stranger's alarm, gate, key fob or car. No exceptions, no 'just to see', no 'just once'.",
    "",
    "# Laws differ by country",
    "What is legal in one country is a crime in another. Rules on network access, interception and radio transmission differ everywhere and change over time.",
    "",
    "It is your job to find out and obey the laws of your own jurisdiction — do not assume, verify. When unsure, treat it as illegal and do not do it until you confirm otherwise.",
    "",
    "# Responsibility is yours alone",
    "All responsibility for use rests solely with the end user — and no one else. The authors accept no liability: not for damage, not for legal consequences. The software is provided 'as is', without warranty.",
    "",
    "# What is in the firmware now",
    "Everything in this build is passive or defensive:",
    "",
    "Wi-Fi and BLE scan - listens to what is already broadcast openly.",
    "",
    "Hidden name reveal - reads a name from management frames that already carry it in cleartext. Receive only.",
    "",
    "Deauth monitor - counts other people's deauth frames to warn you. Receive only.",
    "",
    "# Offensive tools - later, behind a lock",
    "Some future features are active (deauthing your own network to test it, jamming for a bench). They will live in a separate, locked section: each time, access requires confirming the equipment is yours and that you comply with the law. Off by default.",
    "",
    "About jamming: radiating a jammer over the air is illegal almost everywhere - even against your own devices: interference spills into shared spectrum and harms everyone. So it is shielded-bench only, behind the lock.",
    "",
    "# Other people's privacy",
    "Even passive observation can touch someone's privacy. Do not collect data about other people's devices, do not track people, do not publish their MACs or network names.",
    "",
    "By continuing you confirm: you will use this firmware only on your own equipment, you have checked the laws of your own country yourself, and you take all responsibility.",
};

static const LegalDoc LEGAL_DOC_RU = { LEGAL_RU, (int)(sizeof(LEGAL_RU) / sizeof(LEGAL_RU[0])) };
static const LegalDoc LEGAL_DOC_EN = { LEGAL_EN, (int)(sizeof(LEGAL_EN) / sizeof(LEGAL_EN[0])) };
